<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="..\Saas.Application\PharmaAuto.Saas.Application.csproj" />
    <ProjectReference Include="..\Saas.Domain\PharmaAuto.Saas.Domain.csproj" />
    <ProjectReference Include="..\Saas.Infrastructure\PharmaAuto.Saas.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="Seed\canonical-products.v1.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </None>
  </ItemGroup>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
</Project>
